---
apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image
metadata:
  labels:
    serving.knative.dev/release: "v0.11.1"
  name: queue-proxy
  namespace: knative-serving
spec:
  image: ${PRIVATE_REGISTRY}/gcr.io/knative-releases/knative.dev/serving/cmd/queue:v0.11.1


