apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
resources:
- gateway.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-role.yaml
- service-role-binding.yaml
- role-binding.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- apiservice.yaml
- image.yaml
- hpa.yaml
- webhook-configuration.yaml
commonLabels:
  kustomize.component: knative
images:
- name: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newTag: v0.11.1
- name: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa
  newName: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa
  newTag: v0.11.1
- name: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newTag: v0.11.1
- name: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio
  newName: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio
  newTag: v0.11.1
- name: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newTag: v0.11.1
- name: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: $(PRIVATE_REPOSITORY)/gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newTag: v0.11.1
